substitutions:
  _PROJECT_ID: aidetectbypass-464900
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/${_PROJECT_ID}/text-detector-api',
        '-f', 'Dockerfile',
        '.'
      ]
images:
  - 'gcr.io/${_PROJECT_ID}/text-detector-api'
