steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io//text-detector-api',
        '-f', 'Dockerfile',
        '.'
      ]
images:
  - 'gcr.io//text-detector-api'
