steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/text-detector-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/text-detector-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'text-detector-api',
       '--image', 'gcr.io/$PROJECT_ID/text-detector-api',
       '--platform', 'managed',
       '--region', 'us-central1',
       '--allow-unauthenticated']
